### ISSUE TITLE
SUN RGB-D pretrained model depth image format?

### ISSUE THREAD

**Issue by astronautas** [DeepSceneSeg/SSMA#1]
Thank you guys for this awesome contribution to multi-modal semantic segmentation domain! The results seem great!

One question though - did you use colorized depth images (following the OpenCV Jet color scheme) or the grayscale ones (the format that the SUN RGB-D  dataset's images follow) as input for training the Adapnet++ expert with the SUN RGB-D dataset?

**Comment by avalada** [comment]
We report results using standard jet color map as well as using HHA-encoded depth images. We found that HHA-encoded depth performs better in most of the cases. In some earlier papers we experimented with depth as grayscale but that gave us worse performance compared to jet colorized depth.

**Comment by astronautas** [comment]
> We report results using standard jet color map as well as using HHA-encoded depth images. We found that HHA-encoded depth performs better in most of the cases. In some earlier papers we experimented with depth as grayscale but that gave us worse performance compared to jet colorized depth.

Thanks for the clarification!
