### ISSUE TITLE
Depth data preprocessing Cityscape

### ISSUE THREAD

**Issue by LarsShaq** [DeepSceneSeg/SSMA#10]
How is the depth image for the cityscape data created? In the paper a normalization and then jet colormap is mentioned. From the example image it seems that the jet colormap is inverted?

**Comment by mohan1914** [comment]
Cityscapes provide disparity images. Hence, normalization and then jet colormap step results in the inverted jet colormap.

**Comment by chetanmreddy** [comment]
@mohan1914 
Are these the correct steps to prepare cityscapes depth data?
1.convert disparity to depth using `depth = baseline * focal / disparity` 
     for cityscapes baseline = 0.22m and the focal is 2262 for a width of 2048
2. then apply the depth completion
3. finally normalize and apply jet color

or is there anything wrong with this process?
