### ISSUE TITLE
General question about data augmentation

### ISSUE THREAD

**Issue by chetanmreddy** [DeepSceneSeg/SSMA#11]
Hi @avalada , thanks for sharing the code.

As you have mentioned in the paper that you apply certain data augmentation, do you apply each augmentation for all training images individually or all augmentations are applied at once for all training images? I mean like apply rotation+crop+contrast etc at the same time.

**Comment by mohan1914** [comment]
They are randomly applied sequentially meaning there can be just one augmentation of rotation or can be rotation+ contrast and so on.
