### ISSUE TITLE
Could you release data augmentation code?

### ISSUE THREAD

**Issue by githubfragments** [DeepSceneSeg/SSMA#3]
Thanks for your nice work.
Could you release the methods about the data augmentation? As you referred in the paper, include rotatoin, skewing, scaling, vigetting, cropping, brightness modulation, contrast modulation, and flipping.
And the methods of the disparity map converting to jet colorized three channel image, depth completion algorithm, and HHA.
These methods are very helpful for studies.

**Comment by avalada** [comment]
The augmentation code is part of our internal TensorFlow but you can just use normal opencv functions. You can find the HHA computation code here https://github.com/s-gupta/rcnn-depth/blob/master/rcnn/saveHHA.m
The code for depth completion is here https://github.com/kujason/ip_basic

**Comment by githubfragments** [comment]
Thanks very much. 
Another question: did the depth image performance the contrast and brightness modulation?

**Comment by githubfragments** [comment]
> The augmentation code is part of our internal TensorFlow but you can just use normal opencv functions. You can find the HHA computation code here https://github.com/s-gupta/rcnn-depth/blob/master/rcnn/saveHHA.m
> The code for depth completion is here https://github.com/kujason/ip_basic

Did the depth images use the same data augmentation as the rgb images? @avalada

**Comment by avalada** [comment]
We did not use vignetting, brightness and contrast modulation for the depth images.

**Comment by githubfragments** [comment]
Thanks for your replies!
