### ISSUE TITLE
The dilations in the code is not larger than 2, is this normal?

### ISSUE THREAD

**Issue by githubfragments** [DeepSceneSeg/SSMA#5]
Thanks for your nice work!
In your paper (https://arxiv.org/abs/1808.03833), the dilations in the block 3 and block 4 has large dilations, like 2, 4, 8, 16, but in the code the dilations are fixed to 2 (see unit 3, and unit 4). Does this impact the performance?
And in Figure3, the dilations of block3 are r2 = 2, 16, 8, 4, instead of 2, 4, 8, 16, which is right?

**Comment by avalada** [comment]
This was a bug. Should be fixed now.

**Comment by duda1202** [comment]
In the latest code, it is back to stride 2 for all cases. Is it purposeful? Did you find it worked better than the rates in the paper?

**Comment by mohan1914** [comment]
The checkpoints provided were trained with the stride 2 configurations. Hence, the change.
