### ISSUE TITLE
Depth data preparation

### ISSUE THREAD

**Issue by tpatten** [DeepSceneSeg/SSMA#7]
Hi @avalada,

I'm trying to run the RGB_Depth model on scannet. How did you prepare the depth data? I saw in https://github.com/DeepSceneSeg/SSMA/issues/6 that you
1. Depth filled the image
2. Convert to the jet colorspace by dividing by 700 and multiplying by 255

I don't quite understand (2). Can I just use the cv function `depth_img = cv2.applyColorMap(depth_img.astype(np.uint8), cv2.COLORMAP_JET)`?

I get an IoU of 52 when running the RGB model but this drops to 40 when including depth following your instructions.

**Comment by Crocs512** [comment]
I think the input depth is 16bit，so it should be normalized in 0~255. But i can‘t understand that after author's converting then there too many depth value above 255. So what I want to ask is whether there are different scaling factors for the depth maps acquired by different cameras.

**Comment by avalada** [comment]
As mention in #6 we divide by 7000 and multiply by 255. Any value above 255 is clipped. You can see this from choosing 7000 as the maximum depth possible throughout the dataset, whereas the real maximum depth will be much higher, but using it for the scaling between 0-255 resulted in less information for small distances [rounding off to very small range] which is more important. Hence we clip it off to a pseudo maximum in this case 7000.

**Comment by mazeyu** [comment]
I also have some trouble getting good results, the iou is about 45, but I have divided the depth by 7000. Does anybody have some ideas?
And where is the model  "RGB model " as mentioned in the first post?
Thank you.

**Comment by mazeyu** [comment]
> I also have some trouble getting good results, the iou is about 45, but I have divided the depth by 7000. Does anybody have some ideas?
> And where is the model "RGB model " as mentioned in the first post?
> Thank you.

I know, I forget apply jet color map...
