### ISSUE TITLE
Creating the tfrecords file for test data

### ISSUE THREAD

**Issue by mjantoun** [DeepSceneSeg/SSMA#9]
Hello,

I am trying to test the Freiburg Forest model on my RGB dataset.
I am not sure about the txt file that I need to prepare in order to create the tfrecords. I am setting modality1 as the path to the RGB images. What is modality2 and label? I dont have any labels.

**Comment by avalada** [comment]
In case you don't have labels you can either write a new data loader with just modality1 (rgb) or use the given data parser 
by replacing line 52 in convert_to_tfrecords.py provided in the AdapNet-pp repo with label = np.zeros(modality1.shape, np.uint8)
You then will need to only prepare a text file as:
path_to_modality1/0.png

Whereas the convert_to_tfrecords.py in this repo expects RGB Depth and Labels.
